### ISSUE TITLE
Downloadin instead of saving Android

### ISSUE THREAD

**Issue by jbatlleb** [Offroaders123/Smart-Text-Editor#16]
Afer opening a file and editing it in Android, instead of "just saving it", it downloads a new file every time you hit "Save" from File menu.
There's no difference whether the app.is installed or open from the browswer.

**Comment by Offroaders123** [comment]
Unfortunately there isn't a way to fix this for mobile browsers (iOS too), because there aren't any JavaScript APIs that allow for writing directly back to the file system. It is possible in Chromium browsers on desktop, with the File System Access API. That hasn't been implemented on other devices yet though, so unfortunately it has to work that way for the time being. I wish it was possible to do that as well.
